[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[scrolling]
history = 5000

[shell]
args = ["-l", "-c", "tmux new-session -A -s default"]
program = "/bin/zsh"

[window.padding]
x = 10
y = 10
